server:
  port: 7813
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forest_pharmacy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 946626
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off
  application:
    name: forest-pharmacy


# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: '全部'
      paths-to-match: '/**'
      packages-to-scan: com.qing.forestpharmacy
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn

# 文件上传路径
#file_path:
#  path: C:\\Users\\86157\\Desktop\\jetbra\\java\\Forest_Pharmacy\\src\\main\\resources\\static\\images


